services:
  rethink:
    image: rethinkdb
    ports:
      - "8080:8080"
      - "29015:29015"
      - "28015:28015"
  graphql:
    environment:
        - PYTHONUNBUFFERED=1
    build: .
    ports:
        - "8000:8000"
    volumes:
      - .env:/app/.env

