[tool.poetry]
name = "newsletter-website-backend"
version = "0.1.0"
description = ""
authors = ["Sören Michaels <soeren.michaels@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
fastapi = "^0.65.1"
pydantic = "^1.8.2"

[tool.poetry.dev-dependencies]
pylint = "^2.8.3"
uvicorn = "^0.14.0"
jedi = "^0.18.0"

[tool.poetry.scripts]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
